# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50bd05db449d1725b152c79d43ef2970020ba5fec541ffcfd8e3c93024e61cdb3fca56c8ee2efd808f8bab437e8573987a2c35bfbae294e982085a3b6ba02a8c

test:
  secret_key_base: baddabf4a706b8790bb2c57efe3489d9007569d0c05aca42e685a67c60474049c3d075ad9904a15e01a5d48fff13eab5e8d63de762923394ba7dcedfa12a3599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
